/* Author: MyristicaFragrans (https://github.com/MyristicaFragrans)
 * BookHandler.ts (c) 2023
 * Desc: description
 * Created:  2023-07-26T19:23:11.386Z
 */

import {RecordModel as Record} from "pocketbase"
import { useContext } from "preact/hooks";
import PocketContext from "./PocketBaseContext";

// Generated by https://quicktype.io

export interface BookRecord extends Record{
  id:             string;
  author:         string;
  book_name:      string;
  collectionId:   string;
  collectionName: string;
  copies:         number;
  in_use:         number;
  cover:          string;
  expand:         BookRecordExpand;
}

export interface BookRecordExpand {
  author: Author,
  [key: string]: Record | Record[];
}

export interface Author extends Record {
  collectionId:   string;
  collectionName: string;
  created:        string;
  fname:          string;
  id:             string;
  lname:          string;
  profile:        string;
  updated:        string;
}

export interface AuthorExpand {
}

export interface Loan extends Record {
  "id": string,
  "collectionId": string,
  "collectionName": string,
  "user": string,
  "expires": string,
  "bookid": string,
  "type": string,
  "author": string,
  "book_name": string,
  "book": string,
  "cover": string,
  "copies": number,
  expand: BookRecordExpand;
}


export interface BookInterface {
  id: string,
  book_name: string,
  book_cover: string,
  book_text: string,
  copies: number,
  in_use: number,
  author?: AuthorInterface
}
export interface AuthorInterface {
  fname: string,
  lname: string,
  id: string,
  profile: string
}

export function BookRecordToInterface(book: BookRecord | Loan): BookInterface {
  let pb = useContext(PocketContext)
  return {
    id: book.id,
    book_name: book.book_name,
    book_cover: pb.files.getUrl(book, book.cover),
    book_text: book.book,
    copies: book.copies,
    in_use: book.in_use,
    author: {
      id: book.expand.author.id,
      fname: book.expand.author.fname,
      lname: book.expand.author.lname,
      profile: book.expand.author.profile
    }
  }
}